apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-processor
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-processor
  strategy: {}
  template:
    metadata:
      annotations:
        dapr.io/app-id: order-processor
        dapr.io/config: appconfig
        dapr.io/enabled: "true"
        dapr.io/metrics-port: "63509"
        dapr.io/unix-domain-socket-path: ""
      creationTimestamp: null
      labels:
        app: order-processor
    spec:
      containers:
      - env:
        - name: APP_CHANNEL_ADDRESS
        - name: DAPR_METRICS_PORT
          value: "63509"
        - name: APP_ID
          value: order-processor
        imagePullPolicy: Always
        name: order-processor
        resources: {}
