apiVersion: apps/v1
kind: Deployment
metadata:
  name: daprapp
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: daprapp
  strategy: {}
  template:
    metadata:
      annotations:
        dapr.io/app-id: daprapp
        dapr.io/app-port: "3500"
        dapr.io/config: appconfig
        dapr.io/enabled: "true"
        dapr.io/metrics-port: "63089"
        dapr.io/unix-domain-socket-path: ""
      creationTimestamp: null
      labels:
        app: daprapp
    spec:
      containers:
      - env:
        - name: APP_ID
          value: daprapp
        - name: APP_CHANNEL_ADDRESS
        - name: APP_PORT
          value: "3500"
        - name: DAPR_METRICS_PORT
          value: "63089"
        image: dapr_image_name2:tag
        imagePullPolicy: Always
        name: daprapp
        ports:
        - containerPort: 3500
        resources: {}
