apiVersion: apps/v1
kind: Deployment
metadata:
  name: processor
  labels:
    app: processor
    env: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: processor
  template:
    metadata:
      labels:
        app: processor
        env: demo
      annotations:
        dapr.io/enabled: "true"
        dapr.io/id: "processor"
        dapr.io/port: "8081"
        dapr.io/log-as-json: "true"
        dapr.io/config: "tracing"
    spec:
      containers:
      - name: user-container
        image: dapr_image2
        imagePullPolicy: Never
        ports:
        - containerPort: 8081
        env:
        - name: PORT
          value: "8081"
        - name: DAPR_HTTP_PORT
          value: "3500"
        - name: ECOMMERCE_STATE_STORE_NAME
          value: "state-store"

